### ISSUE TITLE
Install via pip leads to urllib3 error

### ISSUE THREAD

**Issue by sjohan99** [mahelbir/valorant-store#4]
Installing via pip and trying to import ValorantStore gives the following error:

```
>>> from valorantstore import ValorantStore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<localpath>\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\valorantstore\__init__.py", line 1, in <module>
    from valorantstore.ValorantStore import ValorantStore
  File "<localpath>\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\valorantstore\ValorantStore.py", line 5, in <module>
    import cfscrape
  File "<localpath>\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cfscrape\__init__.py", line 19, in <module>
    from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (<localpath>\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\util\ssl_.py)
```

Python version: 3.11
OS: Windows 11

Issue can be resolved by downgrading urllib3 to verison <2. i.e `pip install --upgrade 'urllib3<2'`

**Comment by mahelbir** [comment]
Thank you :)
