### ISSUE TITLE
Broken again 😡😡

### ISSUE THREAD

**Issue by XiaXia009** [mahelbir/valorant-store#7]
Traceback (most recent call last):
  File "C:\Users\a0965\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\a0965\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\a0965\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\a0965\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\a0965\OneDrive\桌面\valorant-store-master\valorantstore\ValorantStore.py", line 174, in __login
    cookie = cookie_response.json()
  File "C:\Users\a0965\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\a0965\OneDrive\桌面\valorant-store-master\main.py", line 3, in <module>
    valorant_store = ValorantStore(username="username", password="password", region="ap", sess_path=None, proxy=None)
  File "c:\Users\a0965\OneDrive\桌面\valorant-store-master\valorantstore\ValorantStore.py", line 41, in __init__
    self.__login()
  File "c:\Users\a0965\OneDrive\桌面\valorant-store-master\valorantstore\ValorantStore.py", line 176, in __login
    raise ValorantStoreException("cookie", "request", e, cookie_response)
valorantstore.ValorantStoreException.ValorantStoreException: Cookie: Request error

Need to add a body value
https://valapidocs.techchrism.me/endpoint/auth-cookies
But I can't fix it 😡😡😡

**Comment by XiaXia009** [comment]
Help me delete this issues :(
