### ISSUE TITLE
Request Error when using valorantstore version 6.0.0

### ISSUE THREAD

**Issue by Elivce** [mahelbir/valorant-store#9]
Error:
Traceback (most recent call last):
  File "c:\Users\usern\OneDrive\Documents\Programming\Valorant Account Checker\test.py", line 8, in <module>
    valorant_store = ValorantStore(username="mycorrectusername", password="mycorrectpassword", region="na", sess_path=None, proxy=None)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usern\AppData\Local\Programs\Python\Python311\Lib\site-packages\valorantstore\ValorantStore.py", line 50, in __init__
    self.__login()
  File "C:\Users\usern\AppData\Local\Programs\Python\Python311\Lib\site-packages\valorantstore\ValorantStore.py", line 186, in __login
    raise ValorantStoreException("cookie", "request", cookie_response)
valorantstore.ValorantStoreException.ValorantStoreException: Cookie: Request error

Code
```py
from valorantstore import ValorantStore
valorant_store = ValorantStore(username="username", password="password", region="na", sess_path=None, proxy=None)
print(valorant_store.wallet(False))
```

Can you fix this error

**Comment by Elivce** [comment]
I put my own correct username and password and got the error

**Comment by XiaXia009** [comment]
Have you adjusted it to the correct region?
https://valapidocs.techchrism.me/

**Comment by Elivce** [comment]
> Have you adjusted it to the correct region? https://valapidocs.techchrism.me/

Yes, in the code above im in the region of north america, so I put na.
